### PR TITLE
Adding padre mission to list of used

### PR DESCRIPTION
**Pull request by ehsteve**
I also copied the list to the README to make it more visible to visitors.

### CODE REVIEW

**Comment by ddasilva** [comment]
Glad to hear Padre is using it, that explains the issues created by @scandey.

The images you added to the README don't work, I think you need to edit the paths:
https://github.com/ehsteve/ccsdspy/blob/add_padre/README.rst

Also, under `docs/_static/used-by/` there is a script called `resize.sh` which will resize all the images in the used-by directory to thumbnails and then put them in `used-by/small/`. It depends on imagemagick "convert" command. Can you run this script, add the small version to the pull request, and then reference the small version for the image displayed? This is just a minor thing to make the docs landing page load faster (the image you are adding is 0.6 MB). If installing imagemagick "convert" command is a pain for you, let me know and I'll make the change on your branch.

**Comment by ehsteve** [comment]
@ddasilva this should now be correct. It doesn't show the padre logo in the readme yet as the file is not yet in the repository.

**Comment by ddasilva** [comment]
Looks good to me, thanks!

**Comment by ddasilva** [comment]
I'm going to do a new release soon to get a few of these bugfixes out.  When I do I'll update the public-facing site.

**Pull request merged**
