### PR TITLE
quick fix to keep arrays at the same location as they were declared i…

### PR DESCRIPTION
**Pull request by tloubrieu-jpl**
…n the parsed dictionnary

Fixes  https://github.com/CCSDSPy/ccsdspy/issues/106

That works in my case but I am aware it is not optimally coded.

### CODE REVIEW

**Comment by ddasilva** [comment]
Looks really good!

Can you run `black ccsdspy` from the top-level project directory and commit/repush? If you don't have black run `pip install black`. This will clean up the whitespace. Tests are failing because of this. Will merge when CI passes.

**Comment by tloubrieu-jpl** [comment]
I've just run `black` and pushed the changes. I also added comments.

**Comment by ddasilva** [comment]
Thanks.. it looks like your change added spaces around `**` operators in a couple places, which is causing the CI to fail. Maybe a version mismatch in black? The CI is running black 24.1.1 (latest in PyPI)

**Comment by tloubrieu-jpl** [comment]
Yes, indeed my black version is `21.9b0`. I will upgrade and re-run it, I found weird that it made me change code that I did not touch.

**Comment by tloubrieu-jpl** [comment]
Done. Now it added black lines after some docstrings. I hope this is expected...

**Comment by ddasilva** [comment]
looks good to me, thanks @tloubrieu-jpl !

**Pull request merged**
