### PR TITLE
Implements loading variable length packets from CSV

### PR DESCRIPTION
**Pull request by jmbhughes**
## Purpose

Add support for loading variable length packets from CSV, resolving #115 

Packet array shaped can be defined in the data type as `uint(expand)` for expanding fields or `uint(OPMODE)` for a reference type, where OPMODE is another field. 

## Changes to codebase

- added some new example CSVs to load as variable length packets
- renamed the existing CSVs to reflect the new "basic" versus "extended" nomenclature
- added and used `_parse_csv_array_shape` to handle the more complicated array shape logic
- added test for when `_parse_csv_array_shape` should fail
- added test to confirm proper parsing of `array_shape` 
- added test to confirm variable length packets load from CSV
- updated the documentation to reflect these changes
- required pytest no be less than version 8.1.0

## Todos

- [x] resolve failing CI
- [x] add test for failure cases to make codecov happy
- [ ] unpin pytest version since it appears plugin issue is resolved with new release

## Notes

I think I've implemented all the expected features. I haven't tested extensively, so I can add some more tests if you think it's appropriate. As always, I'm open to suggestions.

### CODE REVIEW

**Comment by jmbhughes** [comment]
@ddasilva the CI failing seems to be because of the release of pytest 8.1.0 a few hours ago and plugins not having updated releases to match necessary changes, namely `pytest-filter-subpackages`(https://github.com/pytest-dev/pytest/issues/11779). You can see the last release of `pytest-filter-subpackages` was in 2022. It looks like [a release is under consideration](https://github.com/astropy/pytest-filter-subpackage/pull/15#issuecomment-1882320033). The simplest solution for now is to not allow pytest 8.1.0 in the CI, but there may be better options.

**Comment by ddasilva** [comment]
> @ddasilva the CI failing seems to be because of the release of pytest 8.1.0 a few hours ago and plugins not having updated releases to match necessary changes, namely `pytest-filter-subpackages`([pytest-dev/pytest#11779](https://github.com/pytest-dev/pytest/issues/11779)). You can see the last release of `pytest-filter-subpackages` was in 2022. It looks like [a release is under consideration](https://github.com/astropy/pytest-filter-subpackage/pull/15#issuecomment-1882320033). The simplest solution for now is to not allow pytest 8.1.0 in the CI, but there may be better options.

Totally reasonable. Feel free to edit your branch to pin a version of pytest and repush.  It would be on this line:
https://github.com/CCSDSPy/ccsdspy/blob/main/pyproject.toml#L36

**Comment by ddasilva** [comment]
Can you write a couple examples in the top comment of this PR? I will send the PR around to some missions that would use this feature to get their feedback.

**Comment by ddasilva** [comment]
@ehsteve Feel free to comment

**Comment by ddasilva** [comment]
I pinged a few of our collaborators over email from Europa Clipper / MMS / Canadian Space Agency to get their thoughts on this new feature. Even if they don't have much to say, it will be good to raise their awareness!
Daniel

**Comment by ddasilva** [comment]
Thanks @jmbhughes !

**Pull request merged**
